# Generated by Django 3.0.8 on 2020-08-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('USERNAME', models.CharField(max_length=20, unique=True)),
                ('PASSWORD', models.CharField(max_length=50)),
                ('EMAILID', models.EmailField(max_length=64)),
                ('ROLE', models.CharField(max_length=10)),
            ],
        ),
    ]
