# Generated by Django 3.0.8 on 2020-08-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0002_remove_login_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=20)),
                ('CATEGORY', models.CharField(max_length=50)),
            ],
        ),
    ]
