# Generated by Django 3.0.8 on 2020-09-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=20)),
                ('CATEGORY', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductPrice', models.CharField(max_length=10)),
                ('ProductQuantity', models.CharField(max_length=15)),
                ('ProductMFGDate', models.DateField()),
                ('ProductEXPDate', models.DateField()),
                ('ProductDeliveryCharge', models.CharField(max_length=5)),
                ('ProductDescription', models.CharField(max_length=500)),
                ('ProductImage1', models.ImageField(null=True, upload_to='product_images/')),
                ('ProductImage2', models.ImageField(null=True, upload_to='product_images/')),
                ('ProductImage3', models.ImageField(null=True, upload_to='product_images/')),
                ('ProductImage4', models.ImageField(null=True, upload_to='product_images/')),
            ],
        ),
    ]
