# Generated by Django 3.0.8 on 2020-10-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductBrand',
            field=models.CharField(default=3, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ProductIngredientType',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ProductManufacturer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ProductManufacturerAddress',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ProductManufacturerContactNo',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ProductManufacturerEmail',
            field=models.CharField(default=4, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ProductNo',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
