# Generated by Django 3.0.8 on 2020-10-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0005_auto_20201001_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=20)),
                ('ShopName', models.CharField(max_length=100)),
                ('ContactNo', models.CharField(max_length=12)),
                ('Email', models.CharField(max_length=64)),
                ('ShopAddress', models.CharField(max_length=500)),
                ('AboutShop', models.CharField(max_length=500)),
                ('GSTNo', models.CharField(max_length=15)),
                ('LicenseNo', models.CharField(max_length=30)),
                ('ShopPhotos1', models.ImageField(null=True, upload_to='vendor_shop_image/')),
                ('ShopPhotos2', models.ImageField(null=True, upload_to='vendor_shop_image/')),
            ],
        ),
    ]
