# Generated by Django 3.0.8 on 2021-03-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0006_vendordetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='USERNAME',
        ),
    ]
