# Generated by Django 3.0.8 on 2021-03-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0007_remove_category_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATEGORY',
            field=models.CharField(max_length=100),
        ),
    ]
