# Generated by Django 3.0.8 on 2021-03-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0008_auto_20210307_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordetails',
            name='ShopPhotos1',
        ),
        migrations.RemoveField(
            model_name='vendordetails',
            name='ShopPhotos2',
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='Status',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
