# Generated by Django 3.0.8 on 2021-03-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0010_vendordetails_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='VendorName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
