# Generated by Django 3.0.8 on 2021-03-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0011_vendordetails_vendorname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductImage2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductImage3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductImage4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductIngredientType',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductManufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductManufacturerAddress',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductManufacturerContactNo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductManufacturerEmail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductNo',
        ),
    ]
