# Generated by Django 3.0.8 on 2021-03-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0012_auto_20210308_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='PINCODE',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='Pincode',
            field=models.CharField(max_length=6),
        ),
    ]
