# Generated by Django 3.0.8 on 2021-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0014_auto_20210309_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductPrice',
            field=models.CharField(max_length=15),
        ),
    ]
