# Generated by Django 3.0.8 on 2021-03-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0015_auto_20210309_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductPrice',
            field=models.CharField(max_length=100),
        ),
    ]
