# Generated by Django 3.0.8 on 2021-03-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0016_auto_20210309_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Status',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
