# Generated by Django 3.0.8 on 2021-03-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0018_auto_20210312_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductPrice',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
