# Generated by Django 3.0.8 on 2021-03-17 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0019_auto_20210312_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerUserName', models.CharField(max_length=20)),
                ('CustomerName', models.CharField(max_length=50)),
                ('CustomerAddress', models.CharField(max_length=500)),
                ('CustomerPhone', models.CharField(max_length=15)),
                ('CustomerEmail', models.EmailField(max_length=64)),
                ('VendorUsername', models.CharField(max_length=20)),
                ('VendorEmail', models.EmailField(max_length=64)),
                ('ShopName', models.CharField(max_length=100)),
                ('ProductId', models.IntegerField(max_length=11)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductQuantity', models.CharField(max_length=15)),
                ('ProductPrice', models.CharField(max_length=10)),
                ('ProductDeliveryCharge', models.CharField(max_length=5)),
                ('PlaceDate', models.DateField(default=datetime.datetime.today)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='USERNAME',
            new_name='VendorUsername',
        ),
    ]
