# Generated by Django 3.0.8 on 2021-03-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0020_auto_20210317_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ProductDeliveryCharge',
        ),
        migrations.AlterField(
            model_name='orders',
            name='ProductId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductPrice',
            field=models.BigIntegerField(),
        ),
    ]
