# Generated by Django 3.0.8 on 2021-03-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0023_product_shopname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ProductImage',
            field=models.ImageField(null=True, upload_to='order_products_images/'),
        ),
    ]
