# Generated by Django 3.0.8 on 2021-05-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0024_orders_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Status',
            field=models.CharField(default='approve', max_length=15),
        ),
    ]
