# Generated by Django 3.0.8 on 2021-05-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0025_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryby',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
