# Generated by Django 3.0.8 on 2021-05-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0028_help_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Notification',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
