# Generated by Django 3.0.8 on 2021-05-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflbuzz', '0029_product_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='PINCODE',
            field=models.CharField(max_length=10),
        ),
    ]
